config/routes.rb
Rails.application.routes.draw do
  resources :splashes
  resources :listings
  devise_for :users
 root to: "splashes#splash"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
end

app/models/splash.rb
class Splash < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    # @listing.id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :user_id, :picture )
    end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  before_action :set_splash, only: [:show, :edit, :update, :destroy]
  
  # loop to make sure you're logged in to get past splash
  def splash
    if user_signed_in?
      redirect_to "/listings/"
    end
  end


  # GET /splashes
  # GET /splashes.json
  def index
    @splashes = Splash.all
  end

  # GET /splashes/1
  # GET /splashes/1.json
  def show
  end

  # GET /splashes/new
  def new
    @splash = Splash.new
  end

  # GET /splashes/1/edit
  def edit
  end

  # POST /splashes
  # POST /splashes.json
  def create
    @splash = Splash.new(splash_params)

    respond_to do |format|
      if @splash.save
        format.html { redirect_to @splash, notice: 'Splash was successfully created.' }
        format.json { render :show, status: :created, location: @splash }
      else
        format.html { render :new }
        format.json { render json: @splash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /splashes/1
  # PATCH/PUT /splashes/1.json
  def update
    respond_to do |format|
      if @splash.update(splash_params)
        format.html { redirect_to @splash, notice: 'Splash was successfully updated.' }
        format.json { render :show, status: :ok, location: @splash }
      else
        format.html { render :edit }
        format.json { render json: @splash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /splashes/1
  # DELETE /splashes/1.json
  def destroy
    @splash.destroy
    respond_to do |format|
      format.html { redirect_to splashes_url, notice: 'Splash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_splash
      @splash = Splash.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def splash_params
      params.fetch(:splash, {})
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PogCafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, min: 1 %>
  </div>

  <div class="field">
  <%= form.label :picture %>
  <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>        

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_options.html.erb
<nav style="display: inline-block; border: 2px white solid;">
<a><%= link_to "View/Create Listings", listings_path, {:style=>'color: white;'} %></a>
<a><%= link_to 'Logout', destroy_user_session_path, method: :delete %></a>
</nav>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
 <%# options partail for nav bar below %>

<p id="notice"><%= notice %></p>
<%= render 'options' %>
<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title |</th>
      <th>Description |</th>
      <th>Price |</th>
      <th>Image</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= image_tag listing.picture, :style => 'max-width: 450px; max-height: 170px;' if listing.picture.attached? %></td>
        <td><%= link_to 'Show', listing, {:style=>'color: white;'} %></td>
        <% if current_user.id == listing.user_id %>
        <td><%= link_to 'Edit', edit_listing_path(listing), {:style=>'color: white;'} %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path, {:style=>'color: white;'} %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<%# code for displaying creator of listing %>
<p>
  <strong>User:</strong>
  <%= @listing.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @listing.picture %>
</p>

<% if current_user.id == @listing.user_id %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>

app/views/splashes/_form.html.erb
<%= form_with(model: splash, local: true) do |form| %>
  <% if splash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(splash.errors.count, "error") %> prohibited this splash from being saved:</h2>

      <ul>
        <% splash.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/splashes/edit.html.erb
<h1>Editing Splash</h1>

<%= render 'form', splash: @splash %>

<%= link_to 'Show', @splash %> |
<%= link_to 'Back', splashes_path %>

app/views/splashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Splashes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @splashes.each do |splash| %>
      <tr>
        <td><%= link_to 'Show', splash %></td>
        <td><%= link_to 'Edit', edit_splash_path(splash) %></td>
        <td><%= link_to 'Destroy', splash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Splash', new_splash_path %>

app/views/splashes/new.html.erb
<h1>New Splash</h1>

<%= render 'form', splash: @splash %>

<%= link_to 'Back', splashes_path %>

app/views/splashes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_splash_path(@splash) %> |
<%= link_to 'Back', splashes_path %>

app/views/splashes/splash.html.erb
<nav style="display: inline-block; border: 2px white solid;">
<a><%= link_to "Home", root_path, {:style=>'color: white;'} %></a>
<a><%= link_to "Create Account", new_user_registration_path, {:style=>'color: white;'} %></a>
<a><%= link_to "Sign In", new_user_session_path, {:style=>'color: white;'} %></a>
</nav>

<h1 style="text-align: center; color: white;">Welcome to PogCafe!</h1>
<%= image_tag("icon.png", alt: 'icon image', :style => 'display: block; margin-left: auto; margin-right: auto; width: 50%;') %>
<h2>Here at PogCafe we aim to make barista quality coffee available to you in the comfort of your own home</h2><br></br>
<h2>Sign up using the links above or Sign in to see listings available or create your own!</h2>